services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: via-user
      POSTGRES_PASSWORD: via-password
      POSTGRES_DB: via-attestation-auto-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: